### ISSUE TITLE
WithHeaderFormatter : Not working

### ISSUE THREAD

**Issue by ramyaDhanush** [rodaine/table#18]
When formatting is applied to header & first column, it is not working 

![image](https://user-images.githubusercontent.com/33391148/137732934-a9913d76-4df9-4a29-b0dd-c31c7455872b.png)

**Comment by QrowPlissken** [comment]
Hello @ramyaDhanush, hope your issue is resolved since.

Maybe I'm wrong, but I think you're on Windows 10 (and by extention, on Powershell).
Powershell ANSI escape support is not enabled by default. You need to enter in Admin Mode and type :

`Set-ItemProperty HKCU:\Console VirtualTerminalLevel -Type DWORD 1` (see [here](https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling/1300251#1300251))

It worked for me for both Powershell version.

On Linux (PopOS!), I had no problem on displaying the table.

Regards,

QrowPlissken
