### ISSUE TITLE
Dynamic headings don't work

### ISSUE THREAD

**Issue by mwgamble** [rodaine/table#30]
I have a need to show dynamic headings in my table. They're specified by the user at runtime. I adapted the example in the readme like so:

```go
package main

import (
  "github.com/fatih/color"
  "github.com/rodaine/table"
)

func main() {
  headings := []string{"ID", "Name", "Score", "Added"}

  headerFmt := color.New(color.FgGreen, color.Underline).SprintfFunc()
  columnFmt := color.New(color.FgYellow).SprintfFunc()

  tbl := table.New(headings...)
  tbl.WithHeaderFormatter(headerFmt).WithFirstColumnFormatter(columnFmt)

  for _, widget := range getWidgets() {
    tbl.AddRow(widget.ID, widget.Name, widget.Cost, widget.Added)
  }

  tbl.Print()
}
```

This doesn't work. I get a compiler error:

```
/test.go:14:20: cannot use headings (variable of type []string) as type []interface{} in argument to table.New
```

I get a similar compile error when trying to call `tbl.AddRow()` by unpacking a slice of strings. They both have the same type signature.

I have a hacky workaround - pass the string slice through this:

```go
func convertStringsToInterfaces(input []string) []interface{} {
	output := make([]interface{}, len(input))
	for i := range input {
		output[i] = input[i]
	}
	return output
}
```

As an inexperienced Go programmer, I'm not really sure why this works, but it does satisfy the compiler. It would be nice to not have to do this though.

**Comment by rodaine** [comment]
Hey @mwgamble! You're running into a bit of a nuance of Go's type system here; namely, Go does not have a concept of covariance. While a `string` satisfies `interface{}`, a `[]string` does not satisfy `[]interface{}`. There's layers to this which get more into the weeds of it (and I'm happy to find more content for you if you're interested), but what's happening in your code is you're taking a `[]string` (`headings`) and attempting to put it into a `[]interface` variable (which the variadic arguments of `table.New` desugars to). This can be fixed by your conversion function above (which is pretty standard for mapping values in Go), or by making the `headings` variable a `[]interface{}` to begin with.

**Comment by mwgamble** [comment]
Thanks! Since I filed this issue I've learned a lot more about Golang's type system generally, but I definitely appreciate the explanation :)

Is there a reason why `table.New()` accepts `interface{}` instead of `string` though? That wasn't intuitive to me.

**Comment by rodaine** [comment]
Just like the rows themselves, the headers can be sourced from any type; the library effectively calls `fmt.Sprint` to get a string value for each. This allows for more dynamic headers if needed.
